name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    uses: valitydev/base-workflow/.github/workflows/maven-service-build.yml@v1
  deploy:
    uses: valitydev/base-workflow/.github/workflows/maven-service-deploy.yml@v1
    with:
      ignore-coverage: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}